/**
 * this is the Item class, it contains the stats for an item, an item can be either a healing item, or a damage boosting item.
 * @author Lieuwe Baron.
 * @author Jan Udeman.
 * @version 23/01/2020.
 */
public class Item {
    String Type;
    int Effect;
    double Weight;
    /**
     * this is the constructior for the Item Class.
     */
    public Item() {
        if(getRandomIntegerBetweenRange(0,1) == 1) {
            this.Type = "Damage";
            this.Effect = 30;
            this.Weight = getRandomDoubleBetweenRange(1.0,2.0);
        } else {
            this.Type = "Healing";
            this.Effect = 50;
            this.Weight = getRandomDoubleBetweenRange(1.0, 2.0);
        }
    }
    /**
     * this method returns the weight of the item.
     * @return: returns the weight of the item.
     */
    public double getWeight() {return this.Weight;}
    /**
     * this method generated a random integer between 2 given values.
     * @param min: the minimum value generated by this method.
     * @param max: the maximum value generated by this method.
     * @return: returns the random integer between the min and the max.
     */
    public static int getRandomIntegerBetweenRange(int min, int max){
        int x = (int)(Math.random()*((max-min)+1))+min;
        return x;
    }
    /**
     * this method generated a random double between 2 given values.
     * @param min: the minimum value generated by this method.
     * @param max: the maximum value generated by this method.
     * @return: returns the random double between the min and the max.
     */
    public static double getRandomDoubleBetweenRange(double min, double max){
        double x = Math.round(((double)(Math.random()*((max-min)+1))+min) * 10)/10.0;
        return x;
    }
}
